AuctionWebApplication/Controllers/AllAuctionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuctionWebApplication;
using Microsoft.AspNetCore.Authorization;

namespace AuctionWebApplication.Controllers
{
    [Authorize(Roles ="admin")]
    public class AllAuctionsController : Controller
    {
        private readonly DbauctionContext _context;

        public AllAuctionsController(DbauctionContext context)
        {
            _context = context;
        }

        // GET: AllAuctions
        public async Task<IActionResult> Index()
        {
            var dbauctionContext = _context.Auctions.Include(a => a.Bid).Include(a => a.Seller);
            return View(await dbauctionContext.ToListAsync());
        }

        // GET: AllAuctions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions
                .Include(a => a.Bid)
                .Include(a => a.Seller)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (auction == null)
            {
                return NotFound();
            }

            return View(auction);
        }

        // GET: AllAuctions/Create
        public IActionResult Create()
        {
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId");
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: AllAuctions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuctionId,SellerId,AuctionName,AuctionDesription,StartPrice,EndTime,BidId")] Auction auction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(auction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId", auction.BidId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId", auction.SellerId);
            return View(auction);
        }

        // GET: AllAuctions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions.FindAsync(id);
            if (auction == null)
            {
                return NotFound();
            }
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId", auction.BidId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId", auction.SellerId);
            return View(auction);
        }

        // POST: AllAuctions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AuctionId,SellerId,AuctionName,AuctionDesription,StartPrice,EndTime,BidId")] Auction auction)
        {
            if (id != auction.AuctionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(auction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuctionExists(auction.AuctionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId", auction.BidId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId", auction.SellerId);
            return View(auction);
        }

        // GET: AllAuctions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions
                .Include(a => a.Bid)
                .Include(a => a.Seller)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (auction == null)
            {
                return NotFound();
            }

            return View(auction);
        }

        // POST: AllAuctions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Auctions == null)
            {
                return Problem("Entity set 'DbauctionContext.Auctions'  is null.");
            }

            var auction = await _context.Auctions.FirstOrDefaultAsync();
            var soldItem = await _context.SoldItems.FindAsync(auction.AuctionId);
            if (soldItem != null) {
                _context.SoldItems.Remove(soldItem);
            }
            if (auction != null)
            {
                _context.Auctions.Remove(auction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuctionExists(int id)
        {
          return (_context.Auctions?.Any(e => e.AuctionId == id)).GetValueOrDefault();
        }
    }
}

AuctionWebApplication/Controllers/MyAuctionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuctionWebApplication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace AuctionWebApplication.Controllers
{
    public class MyAuctionsController : Controller
    {
        private readonly DbauctionContext _context;

        public MyAuctionsController(DbauctionContext context)
        {
            _context = context;
        }

        // GET: MyAuctions
        public async Task<IActionResult> Index()
        {
            var dbauctionContext = _context.Auctions
                .Include(a => a.Seller)
                .Include(a => a.Bid)
                .Where(a => a.SellerId == User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(await dbauctionContext.ToListAsync());
        }

        // GET: MyAuctions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions
                .Include(a => a.Bid)
                .Include(a => a.Seller)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (auction == null)
            {
                return NotFound();
            }

            return View(auction);
        }

        // GET: MyAuctions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MyAuctions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuctionId,SellerId,AuctionName,AuctionDesription,StartPrice,EndTime,BidId")] Auction auction)
        {
            auction.SellerId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _context.Add(auction);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: MyAuctions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions.FindAsync(id);
            if (auction == null)
            {
                return NotFound();
            }
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId", auction.BidId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId", auction.SellerId);
            return View(auction);
        }

        // POST: MyAuctions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AuctionId,SellerId,AuctionName,AuctionDesription,StartPrice,EndTime,BidId")] Auction auction)
        {
            if (id != auction.AuctionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(auction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuctionExists(auction.AuctionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BidId"] = new SelectList(_context.Bids, "BidId", "BidId", auction.BidId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "UserId", auction.SellerId);
            return View(auction);
        }

        // GET: MyAuctions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Auctions == null)
            {
                return NotFound();
            }

            var auction = await _context.Auctions
                .Include(a => a.Bid)
                .Include(a => a.Seller)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (auction == null)
            {
                return NotFound();
            }

            return View(auction);
        }

        // POST: MyAuctions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Auctions == null)
            {
                return Problem("Entity set 'DbauctionContext.Auctions'  is null.");
            }
            var auction = await _context.Auctions.FindAsync(id);
            if (auction != null)
            {
                _context.Auctions.Remove(auction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuctionExists(int id)
        {
          return (_context.Auctions?.Any(e => e.AuctionId == id)).GetValueOrDefault();
        }
    }
}

AuctionWebApplication/Controllers/SoldItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AuctionWebApplication.Models;

namespace AuctionWebApplication.Controllers
{
    public class SoldItemsController : Controller
    {
        private readonly DbauctionContext _context;

        public SoldItemsController(DbauctionContext context)
        {
            _context = context;
        }

        // GET: SoldItems
        public async Task<IActionResult> Index()
        {
            var dbauctionContext = _context.SoldItems.Include(s => s.Bidder).Include(s => s.Auction);
            return View(await dbauctionContext.ToListAsync());
        }

        // GET: SoldItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SoldItems == null)
            {
                return NotFound();
            }

            var soldItem = await _context.SoldItems
                .Include(s => s.Bidder)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (soldItem == null)
            {
                return NotFound();
            }

            return View(soldItem);
        }

        // GET: SoldItems/Create
        public IActionResult Create()
        {
            ViewData["AuctionId"] = new SelectList(_context.Auctions, "AuctionId", "AuctionId");
            ViewData["BidderId"] = new SelectList(_context.Users, "UserId", "UserId");
            return View();
        }

        // POST: SoldItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuctionId,FinalPrice,BidderId")] SoldItem soldItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(soldItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuctionId"] = new SelectList(_context.Auctions, "AuctionId", "AuctionId", soldItem.AuctionId);
            ViewData["BidderId"] = new SelectList(_context.Users, "UserId", "UserId", soldItem.BidderId);
            return View(soldItem);
        }

        // GET: SoldItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SoldItems == null)
            {
                return NotFound();
            }

            var soldItem = await _context.SoldItems.FindAsync(id);
            if (soldItem == null)
            {
                return NotFound();
            }
            ViewData["AuctionId"] = new SelectList(_context.Auctions, "AuctionId", "AuctionId", soldItem.AuctionId);
            ViewData["BidderId"] = new SelectList(_context.Users, "UserId", "UserId", soldItem.BidderId);
            return View(soldItem);
        }

        // POST: SoldItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AuctionId,FinalPrice,BidderId")] SoldItem soldItem)
        {
            if (id != soldItem.AuctionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(soldItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SoldItemExists(soldItem.AuctionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuctionId"] = new SelectList(_context.Auctions, "AuctionId", "AuctionId", soldItem.AuctionId);
            ViewData["BidderId"] = new SelectList(_context.Users, "UserId", "UserId", soldItem.BidderId);
            return View(soldItem);
        }

        // GET: SoldItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SoldItems == null)
            {
                return NotFound();
            }
            
            var soldItem = await _context.SoldItems
                .Include(s => s.Bidder)
                .FirstOrDefaultAsync(m => m.AuctionId == id);
            if (soldItem == null)
            {
                return NotFound();
            }

            return View(soldItem);
        }

        // POST: SoldItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SoldItems == null)
            {
                return Problem("Entity set 'DbauctionContext.SoldItems'  is null.");
            }
            var soldItem = await _context.SoldItems
                .FirstOrDefaultAsync();

            if (soldItem != null)
            {
                _context.SoldItems.Remove(soldItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SoldItemExists(int id)
        {
          return (_context.SoldItems?.Any(e => e.AuctionId == id)).GetValueOrDefault();
        }
    }
}

AuctionWebApplication/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@inject DbauctionContext dbContext
@{
    var user = dbContext.Users.Where(c => c.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).FirstOrDefault();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuctionWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuctionWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Auctions" asp-action="Index">AuctionWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auctions" asp-action="Index">Активні Аукціони</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyAuctions" asp-action="Index">Мої Аукціони</a>
                        </li>
                        }
                        @if (User.FindFirstValue(ClaimTypes.Role) == "admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AllAuctions" asp-action="Index">Усі Аукціони</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SoldItems" asp-action="Index">Продано</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <li>Баланс: @user.Balance &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Доступно: @(user.Balance - user.Freeze)</li>
                            </li>
                        </ul>
                    </div>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <li> @User.Identity.Name</li>
                                </li>
                            </ul>
                        </div>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Вихід</a>
                            </li>
                        </ul>
                    </div>
                         
                }
                else
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вхід</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Реєстрація</a>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>